version: "3.8"

services:
  php:
    container_name: wallet_php
    build:
      context: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/mini-wallet

  nginx:
    container_name: wallet_nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/mini-wallet
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
